---
- name: Installer et configurer Apache sur EC2
  hosts: webserver
  become: yes  
  tasks:
    - name: Mettre à jour les paquets apt (pour Ubuntu)
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes 

    - name: Créer une page HTML par défaut
      copy:
        content: "<h1>Bienvenue sur mon serveur Apache géré par Ansible</h1>"
        dest: /var/www/html/index.html
